<a href="https://colab.research.google.com/github/aandressena/BOOTCAMP-Course/blob/main/Exercises_MonClass_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Exercícios de Monitoria 01

### Tabuada ✓
Imprima a tabuada de 1 ao 10;

In [292]:
import numpy as np

In [293]:
num = np.arange(1, 11)
for x in num:
  print(num * x)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10 12 14 16 18 20]
[ 3  6  9 12 15 18 21 24 27 30]
[ 4  8 12 16 20 24 28 32 36 40]
[ 5 10 15 20 25 30 35 40 45 50]
[ 6 12 18 24 30 36 42 48 54 60]
[ 7 14 21 28 35 42 49 56 63 70]
[ 8 16 24 32 40 48 56 64 72 80]
[ 9 18 27 36 45 54 63 72 81 90]
[ 10  20  30  40  50  60  70  80  90 100]


### Divisiveis por 3 ✓
Considerando os números inteiros de 1 a 100, escreva um código que imprima apenas os números divisíveis por 3;

In [ ]:
for number in range(1,101):
  if number % 3 == 0:
    print(number)

### Imprimir numeros em forma ✓
Imprima os seguintes números na forma abaixo:<br>
1<br>
2 2<br>
3 3 3<br>
4 4 4 4<br>
5 5 5 5 5<br>

In [295]:
n = 0
while n < 5:
  n = n + 1
  print(n * (str(n) + ' '))

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


### Listas pares e impares ✓
Dadas duas listas:<br>
<code>lista1 = [0, 4, 17, 8, 25, 6, 3, 99, 62, 7, 31, 71]<br>
lista2 = [10, 11, 27, 18, 5, 62, 3, 94, 2 ,7]</code><br>
Crie uma nova lista que contenha apenas números impares da primeira lista e números pares da segunda lista;

In [296]:
lista1 = [0, 4, 17, 8, 25, 6, 3, 99, 62, 7, 31, 71]
lista2 = [10, 11, 27, 18, 5, 62, 3, 94, 2 ,7]

In [297]:
lista = []
impar = []
par = []
for n in lista1:
  if n % 2 != int():
    impar.append(n)

for n in lista2:
  if n % 2 == int():
    par.append(n)
    

In [298]:
lista = impar + par

In [299]:
print(impar)
print(par)
print(lista)

[17, 25, 3, 99, 7, 31, 71]
[10, 18, 62, 94, 2]
[17, 25, 3, 99, 7, 31, 71, 10, 18, 62, 94, 2]


### Função < ou > 1000 ✓
Dados dois números inteiros, escreva um código que:
* a) Retorne o produto dos números;
* b) Se o produto for maior que 1000, retorne a soma;
* c) Execute a tarefa acima para duas listas de números;
* d) Execute a tarefa acima em uma função;

In [300]:
#d)
def conta(x, y):
  if x * y < 1000:
    result = (x * y)
    
  else:
    result = (x + y)
  return result


In [301]:
#a) & b)
conta(5, 10)
conta(100, 150)

250

In [302]:
#c)
lista1 = [2, 10, 110]
lista2 = [3, 15, 150]



for l1 in lista1:
  for l2 in lista2:
    if l1 * l2 < 1000:
      print(f'{l1} * {l2} = {conta(l1, l2)}')
    else:
      print(f'{l1} + {l2} = {conta(l1, l2)}')



  

2 * 3 = 6
2 * 15 = 30
2 * 150 = 300
10 * 3 = 30
10 * 15 = 150
10 + 150 = 160
110 * 3 = 330
110 + 15 = 125
110 + 150 = 260
